/**
 * Created by Farouk on 14/06/20.
 */
object Libs {
    const val ACTIVITY_KTX = "androidx.activity:activity-ktx"
    const val ANDROIDX_HILT_COMPILER = "androidx.hilt:hilt-compiler"
    const val APPCOMPAT = "androidx.appcompat:appcompat"
    const val ARCH_TESTING = "androidx.arch.core:core-testing"
    const val ARCH_WORK = "androidx.work:work-runtime-ktx"
    const val BASE_RECYCLER_ADAPTER = "com.github.skydoves:baserecyclerviewadapter"
    const val CARDVIEW = "androidx.cardview:cardview"
    const val CONSTRAINT_LAYOUT = "androidx.constraintlayout:constraintlayout"
    const val CORE_KTX = "androidx.core:core-ktx"
    const val COROUTINES = "org.jetbrains.kotlinx:kotlinx-coroutines-core"
    const val COROUTINES_TEST = "org.jetbrains.kotlinx:kotlinx-coroutines-test"
    const val ESPRESSO_CORE = "androidx.test.espresso:espresso-core"
    const val EXT_JUNIT = "androidx.test.ext:junit"
    const val FRAGMENT_KTX = "androidx.fragment:fragment-ktx"
    const val GLIDE = "com.github.bumptech.glide:glide"
    const val GLIDE_COMPILER = "com.github.bumptech.glide:compiler"
    const val GSON = "com.google.code.gson:gson"
    const val HAMCREST = "org.hamcrest:hamcrest-library"
    const val HILT_ANDROID = "com.google.dagger:hilt-android"
    const val HILT_VIEWMODEL = "androidx.hilt:hilt-lifecycle-viewmodel"
    const val HILT_COMPILER = "com.google.dagger:hilt-android-compiler"
    const val HILT_TESTING = "com.google.dagger:hilt-android-testing"
    const val JUNIT = "junit:junit"
    const val KOTLIN_STDLIB = "org.jetbrains.kotlin:kotlin-stdlib-jdk7"
    const val LIFECYCLE_COMPILER = "androidx.lifecycle:lifecycle-compiler"
    const val LIFECYCLE_LIVE_DATA_KTX = "androidx.lifecycle:lifecycle-livedata-ktx"
    const val LIFECYCLE_VIEW_MODEL_KTX = "androidx.lifecycle:lifecycle-viewmodel-ktx"
    const val MATERIAL = "com.google.android.material:material"
    const val NAVIGATION_FRAGMENT_KTX = "androidx.navigation:navigation-fragment-ktx"
    const val NAVIGATION_UI_KTX = "androidx.navigation:navigation-ui-ktx"
    const val OKHTTP = "com.squareup.okhttp3:okhttp"
    const val OKHTTP_LOGGING_INTERCEPTOR = "com.squareup.okhttp3:logging-interceptor"
    const val ROOM_COMPILER = "androidx.room:room-compiler"
    const val ROOM_KTX = "androidx.room:room-ktx"
    const val ROOM_RUNTIME = "androidx.room:room-runtime"
    const val RULES = "androidx.test:rules"
    const val RUNNER = "androidx.test:runner"
    const val RECYCLER_VIEW = "androidx.recyclerview:recyclerview"
    const val RETROFIT = "com.squareup.retrofit2:retrofit"
    const val RETROFIT_GSON = "com.squareup.retrofit2:converter-gson"
    const val SANDWICH = "com.github.skydoves:sandwich"
    const val SWIPE_REFRESH = "androidx.swiperefreshlayout:swiperefreshlayout"
    const val THREETENABP = "com.jakewharton.threetenabp:threetenabp"
    const val THREETENBP = "org.threeten:threetenbp"
    const val TRANSFORMATION_LAYOUT = "com.github.skydoves:transformationlayout"
    const val TIMBER = "com.jakewharton.timber:timber"
    const val WHATIF = "com.github.skydoves:whatif"
    const val VECTOR_DRAWABLES = "androidx.vectordrawable:vectordrawable"
}